



[tool.uv.sources]
stream-agents = { workspace = true }
stream-agents-plugin-xai = { workspace = true }

[tool.uv.workspace]
members = ["stream-agents", "plugins/*"]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "python-dotenv",
]
