[project]
name = "stream-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "getstream[webrtc]>=2.3.0a0",
    "getstream-plugins-elevenlabs>=0.1.0",
    "python-dotenv>=1.1.1",
]
