[tool.uv.sources]
stream-agents = { workspace = true }
stream-agents-plugins-anthropic = { workspace = true }
stream-agents-plugins-cartesia = { workspace = true }
stream-agents-plugins-deepgram = { workspace = true }
stream-agents-plugins-elevenlabs = { workspace = true }
stream-agents-plugins-fal = { workspace = true }
stream-agents-plugins-gemini = { workspace = true }
stream-agents-plugins-kokoro = { workspace = true }
stream-agents-plugins-moonshine = { workspace = true }
stream-agents-plugins-openai = { workspace = true }
stream-agents-plugins-silero = { workspace = true }
stream-agents-plugins-xai = { workspace = true }
stream-agents-plugins-getstream = { workspace = true }

[tool.uv.workspace]
members = [
    "agents-core",
    "plugins/anthropic",
    "plugins/cartesia",
    "plugins/deepgram",
    "plugins/elevenlabs",
    "plugins/fal",
    "plugins/gemini",
    "plugins/kokoro",
    "plugins/moonshine",
    "plugins/openai",
    "plugins/silero",
    "plugins/xai",
    "plugins/getstream"
]
exclude = [
"**/__pycache__",
"**/tests/__pycache__",
"**/*.pyc",
"**/dist/",
"**/*.egg-info/",
"**/.pytest_cache/",
"**/.mypy_cache/",
"**/.ruff_cache/",
"examples/",
"**/test*",
]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pip>=25.2",
    "pytest",
    "pytest-xdist",
    "pytest-asyncio",
    "python-dotenv",
    "pre-commit",
    "scalene>=1.5.54",
    "fastmcp>=2.12.3",
]

[tool.mypy]
python_version = "3.12"
mypy_path = ["agents-core"]
# Gradual typing → can tighten over time
ignore_missing_imports = true
check_untyped_defs = true
namespace_packages = true
explicit_package_bases = true
