[project]
name = "stream-agents"
version = "0.1.0"
description = "GetStream Agents AI Python SDK - Add AI agents into your video calling applications"
requires-python = ">=3.10,<4.0.0"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "getstream[webrtc]==2.3.0a6"
]

[build-system]
requires = ["hatchling", "hatch-vcs", "setuptools-scm"]
build-backend = "hatchling.build"

[tool.uv.sources]
stream-agents = { workspace = true }
stream-agents-plugin-xai = { workspace = true }

[tool.uv.workspace]
members = ["stream-agents", "plugins/*"]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "pytest-xdist",
    "pytest-asyncio",
    "python-dotenv",
    "pre-commit",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "vcs"
raw-options = { root = "..", search_parent_directories = true, fallback_version = "0.0.0" }



[tool.mypy]
python_version = "3.12"
files = ["stream-agents/stream_agents", "plugins", "tests"]

# Gradual typing → can tighten over time
ignore_missing_imports = true
check_untyped_defs = true

