[tool.uv.sources]
stream-agents = { workspace = true }

[tool.uv.workspace]
members = ["stream-agents", "plugins/*"]
exclude = [
"**/__pycache__",
"**/tests/__pycache__",
"**/*.pyc",
"**/dist/",
"**/*.egg-info/",
"**/.pytest_cache/",
"**/.mypy_cache/",
"**/.ruff_cache/",
"examples/",
"**/test*",
]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pip>=25.2",
    "pytest",
    "pytest-xdist",
    "pytest-asyncio",
    "python-dotenv",
    "pre-commit",
]

[tool.mypy]
python_version = "3.12"
files = ["stream-agents/src/stream_agents", "plugins", "tests"]

# Gradual typing → can tighten over time
ignore_missing_imports = true
check_untyped_defs = true
namespace_packages = true
explicit_package_bases = true

