



[tool.uv.sources]
stream-agents = { workspace = true }
stream-agents-plugin-xai = { workspace = true }

[tool.uv.workspace]
members = ["stream-agents", "plugins/*"]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pytest",
    "python-dotenv",
    "pip>=25.2",
]

[tool.mypy]
python_version = "3.12"
files = ["stream-agents/stream_agents", "plugins", "tests"]

# Gradual typing → can tighten over time
ignore_missing_imports = true
check_untyped_defs = true
