[tool.uv.sources]
stream-agents = { workspace = true }
stream-agents-plugin-anthropic = { workspace = true }
getstream-plugins-cartesia = { workspace = true }
getstream-plugins-deepgram = { workspace = true }
getstream-plugins-elevenlabs = { workspace = true }
getstream-plugins-fal = { workspace = true }
getstream-plugins-gemini = { workspace = true }
getstream-plugins-kokoro = { workspace = true }
getstream-plugins-moonshine = { workspace = true }
getstream-plugins-openai = { workspace = true }
getstream-plugins-silero = { workspace = true }
stream-agents-plugin-xai = { workspace = true }

[tool.uv.workspace]
members = [
    "stream-agents", 
    "plugins/anthropic",
    "plugins/cartesia", 
    "plugins/deepgram",
    "plugins/elevenlabs",
    "plugins/fal",
    "plugins/gemini",
    "plugins/kokoro",
    "plugins/moonshine",
    "plugins/openai",
    "plugins/silero",
    "plugins/xai"
]
exclude = [
"**/__pycache__",
"**/tests/__pycache__",
"**/*.pyc",
"**/dist/",
"**/*.egg-info/",
"**/.pytest_cache/",
"**/.mypy_cache/",
"**/.ruff_cache/",
"examples/",
"**/test*",
]

[dependency-groups]
dev = [
    "ruff",
    "mypy",
    "pip>=25.2",
    "pytest",
    "pytest-xdist",
    "pytest-asyncio",
    "python-dotenv",
    "pre-commit",
]

[tool.mypy]
python_version = "3.12"
files = ["stream-agents/src/stream_agents", "plugins", "tests"]

# Gradual typing → can tighten over time
ignore_missing_imports = true
check_untyped_defs = true
namespace_packages = true
explicit_package_bases = true

