[project]
name = "docs-agent-example"
version = "0.0.0"
requires-python = ">=3.13,<3.14"

# Dependencies that the example actually uses
dependencies = [
  "python-dotenv>=1.0",
  "vision-agents-plugins-stream",
  "vision-agents",
]

[tool.uv.sources]
"vision-agents-plugins-stream" = {path = "../../../plugins/stream", editable=true}
"vision-agents" = {path = "../../../sdks/python", editable=true}
