name: Python + uv setup
description: Checkout, set up uv/Python, and sync dev deps
inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.13"
  sync-flags:
    description: Extra flags for uv sync (e.g., --all-extras --dev)
    required: false
    default: "--all-extras --dev"
  working-directory:
    description: Directory to run in
    required: false
    default: "."
runs:
  using: composite
  steps:
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"
        version: "latest"
        enable-cache: true
        cache-dependency-glob: |
          **/pyproject.toml
          **/uv.lock
    - name: Log cache status
      shell: bash
      env:
        UV_CACHE_HIT: "${{ steps.setup_uv.outputs['cache-hit'] }}"
      run: |
        echo "setup-uv cache hit: ${UV_CACHE_HIT}"

    - name: Install the project
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: uv sync --all-extras --dev
