import asyncio
from uuid import uuid4
from dotenv import load_dotenv

from vision_agents.core import User, Agent
from vision_agents.plugins import getstream, gemini, heygen

load_dotenv()


async def start_avatar_agent() -> None:
    """Start an agent with HeyGen avatar using Realtime LLM.
    
    This example demonstrates how to use HeyGen's avatar streaming
    with Gemini Realtime. The avatar will lip-sync with the audio
    generated by the Realtime LLM.
    """
    
    # Create agent with HeyGen avatar and Realtime LLM
    agent = Agent(
        edge=getstream.Edge(),
        agent_user=User(
            name="AI Assistant with Avatar",
            id="agent"
        ),
        instructions=(
            "You're a friendly and helpful AI assistant. "
            "Keep your responses conversational and engaging. "
            "Don't use special characters or formatting."
        ),
        
        # Use Gemini Realtime (includes built-in TTS and STT)
        llm=gemini.Realtime(fps=2),
        
        # Add HeyGen avatar as a video publisher
        processors=[
            heygen.AvatarPublisher(
                avatar_id="default",  # Use your HeyGen avatar ID
                quality="high",       # Video quality: "low", "medium", "high"
                resolution=(1920, 1080),  # Output resolution
            )
        ]
    )
    
    # Create a call
    call = agent.edge.client.video.call("default", str(uuid4()))
    
    # Join the call
    with await agent.join(call):
        # Set agent reference on avatar publisher for audio event subscription
        avatar_publisher = agent.video_publishers[0]
        if hasattr(avatar_publisher, 'set_agent'):
            avatar_publisher.set_agent(agent)
        
        # Open demo UI
        await agent.edge.open_demo(call)
        
        # Keep the call running - Realtime mode handles conversation automatically
        await agent.finish()


if __name__ == "__main__":
    asyncio.run(start_avatar_agent())

