
class TestRoboflowLocalDetectionProcessor:

    def test_init(self): ...

    def test_process_video(self): ...

    def test_close(self): ...

    def test_warmup(self): ...


class TestRoboflowCloudDetectionProcessor:
    """Test cases for RoboflowDetectionProcessor."""

    def test_init(self): ...

    def test_process_video(self): ...

    def test_close(self): ...

    def test_warmup(self): ...
