[project]
name = "simple-agents-example"
version = "0.0.0"
requires-python = ">=3.10"

# put only what this example needs
dependencies = [
  "python-dotenv>=1.0",
  "getstream[webrtc]==2.3.0a3",
]

[tool.uv.sources]
agents = {path = "../../../stream-agents", editable=true}