name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Core Agent
        - LLM Integration (OpenAI/Gemini/Claude)
        - STT (Speech-to-Text)
        - TTS (Text-to-Speech)
        - Video Processing
        - Audio Processing
        - Plugin System
        - Edge/Stream Integration
        - Examples
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: plugin
    attributes:
      label: Plugin (if applicable)
      description: Which plugin is affected?
      options:
        - Not applicable
        - anthropic
        - cartesia
        - deepgram
        - elevenlabs
        - gemini
        - getstream
        - kokoro
        - krisp
        - moonshine
        - openai
        - silero
        - smart_turn
        - ultralytics
        - wizper
        - xai
        - Other
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04]
        - Python version: [e.g., 3.12.11]
        - Vision Agents version: [e.g., 0.1.0]
        - Plugin versions: [e.g., openai-plugin 0.1.0]
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code to reproduce the issue
      render: python
      placeholder: |
        ```python
        # Your code here
        ```
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error messages or logs
      render: shell
      placeholder: |
        ```
        Paste error logs here
        ```
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...
    validations:
      required: false
