name: Feature Request
description: Suggest an idea for this project.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please explain your use case and proposed solution.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature necessary? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: checkboxes
    id: contributions
    attributes:
      label: Willingness to contribute
      options:
        - label: I can contribute this feature myself!
          required: false
