name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you need this feature?
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you implement it?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any other approaches considered?
