// Package api holds the hand-written half of the router's OpenAPI document.
//
// legacy.yaml describes the operations still generated by oapi-codegen. Every other
// operation is declared in Go with Huma, and openapi.yaml is the two merged by
// cmd/openapi: that file is generated, and legacy.yaml shrinks as operations move to Go.
package api

import _ "embed"

// Legacy is legacy.yaml, including the operations oapi-codegen is told to skip, which
// its own embedded spec leaves out.
//
//go:embed legacy.yaml
var Legacy []byte
