//! Regenerates `src/types.rs` and `src/operations.rs` from the router's OpenAPI spec.
//!
//! `cargo run -p generate` writes both; `cargo run -p generate -- --check` fails when either
//! differs from what is committed.

use std::fmt::Write as _;
use std::io::Write as _;
use std::path::PathBuf;
use std::process::ExitCode;
use std::process::{Command, Stdio};

use heck::{ToPascalCase, ToSnakeCase};
use quote::ToTokens;
use serde_json::{Map, Value, json};
use typify::{TypeSpace, TypeSpaceSettings};
use yaml_rust2::{Yaml, YamlLoader};

const HEADER: &str =
    "// Generated by `cargo run -p generate` from acceleration/api/openapi.yaml. Do not edit.\n";

fn main() -> ExitCode {
    let check = std::env::args().any(|argument| argument == "--check");
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    let spec_path = root.join("../../acceleration/api/openapi.yaml");

    let raw = std::fs::read_to_string(&spec_path).expect("reading the spec");
    let spec = to_json(&YamlLoader::load_from_str(&raw).expect("parsing the spec")[0]);

    let outputs = [
        (root.join("src/types.rs"), rustfmt(&types(&spec))),
        (root.join("src/operations.rs"), rustfmt(&operations(&spec))),
    ];

    let mut stale = false;
    for (path, generated) in outputs {
        if check {
            if std::fs::read_to_string(&path).unwrap_or_default() != generated {
                eprintln!("{} is out of date with the spec", path.display());
                stale = true;
            }
        } else {
            std::fs::write(&path, generated).expect("writing generated code");
            println!("wrote {}", path.display());
        }
    }
    if stale {
        ExitCode::FAILURE
    } else {
        ExitCode::SUCCESS
    }
}

/// Formats the way `cargo fmt` would, so the committed files pass `cargo fmt --check` as well
/// as `--check` here.
fn rustfmt(source: &str) -> String {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .expect("running rustfmt; rustup component add rustfmt");
    child
        .stdin
        .take()
        .expect("stdin")
        .write_all(source.as_bytes())
        .expect("writing to rustfmt");
    let output = child.wait_with_output().expect("rustfmt");
    assert!(
        output.status.success(),
        "rustfmt refused the generated code"
    );
    String::from_utf8(output.stdout).expect("rustfmt writes UTF-8")
}

/// The component schemas as Rust types, through typify.
fn types(spec: &Value) -> String {
    let mut definitions = Map::new();
    for (name, schema) in spec["components"]["schemas"].as_object().expect("schemas") {
        definitions.insert(name.clone(), json_schema(schema));
    }
    let root: schemars::schema::RootSchema = serde_json::from_value(json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "definitions": definitions,
    }))
    .expect("the converted schemas are JSON Schema");

    let mut settings = TypeSpaceSettings::default();
    settings
        .with_struct_builder(false)
        .with_derive("PartialEq".to_string())
        .with_map_type("::std::collections::BTreeMap".to_string());
    let mut space = TypeSpace::new(&settings);
    space
        .add_root_schema(root)
        .expect("typify accepts the schemas");

    let mut file = syn::parse2::<syn::File>(space.to_stream()).expect("typify emits Rust");
    defaults(&mut file);
    format!(
        "{HEADER}//! Every schema in the spec, as a Rust type.\n#![allow(clippy::all, missing_docs)]\n\n{}",
        prettyplease::unparse(&file)
    )
}

/// Derives `Default` on every struct whose fields all have one, so a request is written as the
/// fields it sets followed by `..Default::default()` rather than every field of the schema.
fn defaults(file: &mut syn::File) {
    let derive = syn::parse_str::<syn::ItemStruct>("#[derive(Default)] struct Placeholder;")
        .expect("a derive")
        .attrs
        .remove(0);
    for item in &mut file.items {
        let syn::Item::Struct(declared) = item else {
            continue;
        };
        let syn::Fields::Named(fields) = &declared.fields else {
            continue;
        };
        let derived = declared.attrs.iter().any(|attribute| {
            attribute.path().is_ident("derive")
                && attribute
                    .meta
                    .to_token_stream()
                    .to_string()
                    .contains("Default")
        });
        let defaultable = !derived
            && fields.named.iter().all(|field| match &field.ty {
                syn::Type::Path(kind) => kind.path.segments.last().is_some_and(|last| {
                    matches!(
                        last.ident.to_string().as_str(),
                        "Option"
                            | "Vec"
                            | "Map"
                            | "BTreeMap"
                            | "String"
                            | "bool"
                            | "i64"
                            | "f64"
                            | "Value"
                    )
                }),
                _ => false,
            });
        if defaultable {
            declared.attrs.push(derive.clone());
        }
    }
}

/// Rewrites an OpenAPI 3.0 schema as the JSON Schema typify reads.
///
/// Defaults are dropped so a field the caller left out is left out of the request rather than
/// filled in with the spec's default: a config's own choice must survive a request that said
/// nothing about it. Formats and constraints that would turn a string or an integer into a
/// newtype are dropped too; the router validates them, and a newtype per pattern would be a
/// type per field for a caller to construct.
fn json_schema(schema: &Value) -> Value {
    match schema {
        Value::Object(object) => {
            let mut converted = Map::new();
            for (key, value) in object {
                match key.as_str() {
                    "$ref" => {
                        let name = value
                            .as_str()
                            .expect("a ref")
                            .trim_start_matches("#/components/schemas/");
                        converted.insert(key.clone(), json!(format!("#/definitions/{name}")));
                    }
                    "default" | "example" | "nullable" | "pattern" | "minLength" | "maxLength"
                    | "minimum" | "maximum" | "exclusiveMinimum" | "exclusiveMaximum" => {}
                    "format"
                        if !matches!(
                            value.as_str(),
                            Some("int64" | "int32" | "double" | "float")
                        ) => {}
                    "properties" => {
                        let properties = value
                            .as_object()
                            .expect("properties")
                            .iter()
                            .map(|(name, property)| (name.clone(), json_schema(property)))
                            .collect();
                        converted.insert(key.clone(), Value::Object(properties));
                    }
                    _ => {
                        converted.insert(key.clone(), json_schema(value));
                    }
                }
            }
            if object.get("nullable") == Some(&Value::Bool(true))
                && let Some(Value::String(kind)) = converted.get("type").cloned()
            {
                converted.insert("type".into(), json!([kind, "null"]));
            }
            // An optional list left out and one sent empty mean different things (no skills
            // named leaves the built-in set; an empty list turns delegation off), so an optional
            // list is an Option rather than a Vec skipped when empty.
            let required: Vec<Value> = object
                .get("required")
                .and_then(Value::as_array)
                .cloned()
                .unwrap_or_default();
            if let Some(Value::Object(properties)) = converted.get_mut("properties") {
                for (name, property) in properties.iter_mut() {
                    if property["type"] == "array" && !required.contains(&json!(name)) {
                        property["type"] = json!(["array", "null"]);
                    }
                }
            }
            Value::Object(converted)
        }
        Value::Array(items) => Value::Array(items.iter().map(json_schema).collect()),
        other => other.clone(),
    }
}

/// One method on `Client` per operation that answers over plain HTTP.
///
/// The sockets and the log stream are left out: OpenAPI stops at the upgrade, so those are
/// written by hand in `socket.rs`.
fn operations(spec: &Value) -> String {
    let mut methods = String::new();
    let mut queries = String::new();

    let paths = spec["paths"].as_object().expect("paths");
    for (path, item) in paths {
        let shared = item
            .get("parameters")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
        for method in ["get", "post", "put", "patch", "delete"] {
            let Some(operation) = item.get(method) else {
                continue;
            };
            if streams(operation) {
                continue;
            }
            let id = operation["operationId"].as_str().expect("operationId");
            let name = id.to_snake_case();

            let mut parameters: Vec<Value> = shared.iter().map(|p| resolve(spec, p)).collect();
            if let Some(own) = operation.get("parameters").and_then(Value::as_array) {
                parameters.extend(own.iter().map(|p| resolve(spec, p)));
            }

            let mut arguments = Vec::new();
            let mut route = path.clone();
            for parameter in parameters.iter().filter(|p| p["in"] == "path") {
                let key = parameter["name"].as_str().expect("a name");
                let argument = rust_name(key);
                route = route.replace(&format!("{{{key}}}"), &format!("{{{argument}}}"));
                arguments.push(format!("{argument}: &str"));
            }
            let segments: Vec<String> = parameters
                .iter()
                .filter(|p| p["in"] == "path")
                .map(|p| {
                    let argument = rust_name(p["name"].as_str().expect("a name"));
                    format!("{argument} = segment({argument})")
                })
                .collect();

            let query: Vec<&Value> = parameters.iter().filter(|p| p["in"] == "query").collect();
            let query_type = format!("{}Query", id.to_pascal_case());
            if !query.is_empty() {
                arguments.push(format!("query: &{query_type}"));
                write_query(&mut queries, &query_type, id, &query);
            }

            let body = operation.get("requestBody").map(|body| {
                let schema = &body["content"]["application/json"]["schema"];
                let kind = rust_type(schema);
                if body.get("required") == Some(&Value::Bool(true)) {
                    arguments.push(format!("body: &{kind}"));
                    "Some(body)".to_string()
                } else {
                    arguments.push(format!("body: Option<&{kind}>"));
                    "body".to_string()
                }
            });

            let answer = answer(operation);
            let summary = operation
                .get("summary")
                .and_then(Value::as_str)
                .unwrap_or(id);
            let route_expression = if segments.is_empty() {
                format!("\"{route}\"")
            } else {
                format!("&format!(\"{route}\", {})", segments.join(", "))
            };
            let query_expression = if query.is_empty() {
                "None::<&()>".to_string()
            } else {
                "Some(query)".to_string()
            };
            let body_expression = body.unwrap_or_else(|| "None::<&()>".to_string());
            let signature = std::iter::once("&self".to_string())
                .chain(arguments)
                .collect::<Vec<_>>()
                .join(", ");

            writeln!(
                methods,
                "    /// {summary}\n    ///\n    /// `{} {path}` (`{id}`).\n    pub async fn {name}({signature}) -> Result<{answer}> {{\n        self.send(Method::{}, {route_expression}, {query_expression}, {body_expression}, \"{id}\").await\n    }}\n",
                method.to_uppercase(),
                method.to_uppercase(),
            )
            .unwrap();
        }
    }

    let source = format!(
        "{HEADER}//! One method per HTTP operation in the spec.\n#![allow(clippy::too_many_arguments)]\n\nuse reqwest::Method;\nuse serde::Serialize;\n\nuse crate::client::{{Client, segment}};\nuse crate::error::Result;\nuse crate::types;\n\nimpl Client {{\n{methods}}}\n\n{queries}"
    );
    let file = syn::parse_file(&source).expect("the generated operations are Rust");
    prettyplease::unparse(&file)
}

fn write_query(out: &mut String, name: &str, id: &str, parameters: &[&Value]) {
    writeln!(
        out,
        "/// The query string `{id}` takes. A field left `None` is left out."
    )
    .unwrap();
    writeln!(
        out,
        "#[derive(Debug, Clone, Default, PartialEq, Serialize)]\npub struct {name} {{"
    )
    .unwrap();
    for parameter in parameters {
        let key = parameter["name"].as_str().expect("a name");
        let field = rust_name(key);
        if let Some(description) = parameter.get("description").and_then(Value::as_str) {
            for line in description.trim().lines() {
                writeln!(out, "    /// {}", line.trim()).unwrap();
            }
        }
        if field != key {
            writeln!(out, "    #[serde(rename = \"{key}\")]").unwrap();
        }
        writeln!(
            out,
            "    #[serde(skip_serializing_if = \"Option::is_none\")]\n    pub {field}: Option<{}>,",
            scalar(&parameter["schema"])
        )
        .unwrap();
    }
    writeln!(out, "}}\n").unwrap();
}

/// Whether an operation is a socket or a stream rather than a request and an answer.
fn streams(operation: &Value) -> bool {
    let responses = operation["responses"].as_object().expect("responses");
    responses.contains_key("101")
        || responses.values().any(|response| {
            response
                .get("content")
                .and_then(Value::as_object)
                .is_some_and(|content| content.keys().any(|kind| kind != "application/json"))
        })
}

/// What a successful answer decodes as. An operation that may answer 204 as well as a body
/// answers `Option`, since the empty answer is one of the things it says.
fn answer(operation: &Value) -> String {
    let responses = operation["responses"].as_object().expect("responses");
    let mut body = None;
    let mut empty = false;
    for (status, response) in responses {
        if !status.starts_with('2') {
            continue;
        }
        match response
            .get("content")
            .and_then(|content| content.get("application/json"))
        {
            Some(content) => body = Some(rust_type(&content["schema"])),
            None => empty = true,
        }
    }
    match (body, empty) {
        (Some(kind), true) => format!("Option<{kind}>"),
        (Some(kind), false) => kind,
        (None, _) => "()".to_string(),
    }
}

fn rust_type(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return format!(
            "types::{}",
            reference.trim_start_matches("#/components/schemas/")
        );
    }
    if schema["type"] == "array" {
        return format!("Vec<{}>", rust_type(&schema["items"]));
    }
    "serde_json::Value".to_string()
}

fn scalar(schema: &Value) -> &'static str {
    match schema["type"].as_str() {
        Some("integer") => "i64",
        Some("number") => "f64",
        Some("boolean") => "bool",
        _ => "String",
    }
}

fn rust_name(key: &str) -> String {
    let name = key.to_snake_case();
    if name == "type" {
        "kind".to_string()
    } else {
        name
    }
}

fn resolve(spec: &Value, parameter: &Value) -> Value {
    match parameter.get("$ref").and_then(Value::as_str) {
        Some(reference) => {
            let name = reference.trim_start_matches("#/components/parameters/");
            spec["components"]["parameters"][name].clone()
        }
        None => parameter.clone(),
    }
}

fn to_json(yaml: &Yaml) -> Value {
    match yaml {
        Yaml::Hash(hash) => {
            let mut object = Map::new();
            for (key, value) in hash {
                let key = match key {
                    Yaml::String(text) => text.clone(),
                    Yaml::Integer(number) => number.to_string(),
                    other => panic!("an unexpected key {other:?}"),
                };
                object.insert(key, to_json(value));
            }
            Value::Object(object)
        }
        Yaml::Array(items) => Value::Array(items.iter().map(to_json).collect()),
        Yaml::String(text) => Value::String(text.clone()),
        Yaml::Integer(number) => json!(number),
        Yaml::Real(text) => json!(text.parse::<f64>().expect("a number")),
        Yaml::Boolean(flag) => Value::Bool(*flag),
        Yaml::Null => Value::Null,
        other => panic!("unexpected YAML {other:?}"),
    }
}
