[project]
name = "getstream-events-system-example"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "stream-agents",
]

[tool.uv.sources]
getstream = { path = "../../", editable = true }
stream-agents = { workspace = true }
