package llmrouter

import (
	"context"
	"errors"
	"github.com/openai/openai-go/v3"
	"sync"
	"time"

	"github.com/GetStream/Vision-Agents/acceleration/internal/llm"
	"github.com/GetStream/Vision-Agents/acceleration/internal/quota"
	"github.com/GetStream/Vision-Agents/acceleration/internal/routing"
)

// Session is a live model attached to one customer. It hands out the provider's streams
// untouched apart from recording a stat row per response on the way past.
type Session struct {
	mu       sync.Mutex
	closed   bool
	children map[*Session]struct{}
	fallback func(context.Context, llm.ResponseParams) (*llm.Stream, error)
	provider Provider
	// config is the routing identity of the provider. Stats and health are keyed by it,
	// so a provider registered under a different name still aggregates coherently.
	config   routing.ProviderConfig
	owner    routing.Owner
	recorder *routing.Recorder
	// quota caps what the owner's end user may spend in a day. Nil caps nothing.
	quota *quota.Limiter
}

func newSession(
	provider Provider,
	config routing.ProviderConfig,
	owner routing.Owner,
	recorder *routing.Recorder,
	limiter *quota.Limiter,
) *Session {
	return &Session{
		provider: provider,
		config:   config,
		owner:    owner,
		recorder: recorder,
		quota:    limiter,
	}
}

// Create asks the selected provider for a response. The stream it returns records what the
// response cost as it is drained, which is why a caller must drain it even after closing
// it: an abandoned response still generated tokens.
func (s *Session) create(ctx context.Context, params llm.ResponseParams) (*llm.Stream, error) {
	startedAt := time.Now().UTC()

	stream, err := s.provider.Create(ctx, params)
	if err != nil {
		s.recorder.Record(s.config, routing.Stat{
			Owner:        s.owner,
			StartedAt:    startedAt,
			Success:      false,
			ErrorCode:    "create_failed",
			ErrorMessage: err.Error(),
		})
		return nil, err
	}
	return stream.Observe(func(event llm.Event) { s.observe(startedAt, event) }), nil
}

// Provider is the provider serving this session.
func (s *Session) Provider() string { return s.config.Provider }

// Model is the model serving this session.
func (s *Session) Model() string { return s.config.Model }

// Capabilities is what the model serving this session accepts.
func (s *Session) Capabilities() llm.Capabilities { return s.provider.Capabilities() }

// Price is what this session's provider charges, so a caller can report a cost without
// reaching for the router's config.
func (s *Session) Price() routing.Price { return s.config.Price }

// LLM exposes the underlying provider so callers can reach provider-specific features.
func (s *Session) LLM() llm.LLM { return s.provider }

// Close ends the session, abandoning anything still in flight.
func (s *Session) Close() error {
	s.mu.Lock()
	s.closed = true
	children := make([]*Session, 0, len(s.children))
	for child := range s.children {
		children = append(children, child)
	}
	s.mu.Unlock()
	var failures []error
	for _, child := range children {
		failures = append(failures, child.Close())
	}
	return errors.Join(append(failures, s.provider.Close())...)
}

// observe records statistics as a response settles.
//
// One response is one unit of billable work, the way one synthesis is for text-to-speech,
// and it is recorded once: a failure is carried on the response that failed rather than
// written as a row of its own, so one turn stays one row.
func (s *Session) observe(startedAt time.Time, event llm.Event) {
	completed, settled := event.(llm.ResponseCompleted)
	if !settled {
		return
	}

	response := completed.Response

	// The debit is taken here rather than where the response was asked for, because what a
	// response costs is only known once it has settled. A caller who slipped in under the
	// limit and then spent the rest of the day's tokens in one answer is refused the next
	// one, which is the most a limit counted after the fact can do.
	//
	// Its context is not the one the response was created with: that one is cancelled when
	// the caller hangs up, and a response generated by somebody who hung up before reading
	// it cost exactly as much as one they read.
	s.quota.Debit(context.Background(), s.owner.CustomerID, s.owner.Caller,
		response.Usage.InputTokens+response.Usage.OutputTokens)

	s.recorder.Record(s.config, routing.Stat{
		Owner:     s.owner,
		StartedAt: startedAt,
		Usage: routing.Usage{
			InputTokens:       response.Usage.InputTokens,
			CachedInputTokens: response.Usage.InputTokensDetails.CachedTokens,
			OutputTokens:      response.Usage.OutputTokens,
		},
		// Time to first token is what the caller actually waited for; the rest of the
		// answer arrives while they are already reading or hearing it.
		LatencyMs: response.TimeToFirstTokenMs,
		Success:   response.Status != llm.StatusFailed,
		ErrorCode: errorCode(response),
	})
}

// errorCode says why a response failed, or nothing for one that did not.
func errorCode(response llm.Response) string {
	if response.Status != llm.StatusFailed {
		return ""
	}
	return "provider_error"
}

// Only requests that have not started streaming can be replayed safely. A partial
// answer or tool call is never retried, and provider-held history cannot transfer.
func (s *Session) Create(ctx context.Context, params llm.ResponseParams) (*llm.Stream, error) {
	s.mu.Lock()
	closed := s.closed
	s.mu.Unlock()
	if closed {
		return nil, errors.New("llmrouter: session is closed")
	}
	// The limit is asked here rather than only when the session was opened, because a
	// session answers many turns: a socket goes on sending frames and a call goes on
	// talking long after whatever opened it was let through.
	if err := s.quota.Allow(ctx, s.owner.CustomerID, s.owner.Caller); err != nil {
		return nil, err
	}
	stream, err := s.create(ctx, params)
	if err == nil || ctx.Err() != nil || s.fallback == nil || params.PreviousResponseID != "" || params.Conversation != "" {
		return stream, err
	}
	var apiError *openai.Error
	if errors.As(err, &apiError) && apiError.StatusCode < 500 && apiError.StatusCode != 401 && apiError.StatusCode != 403 && apiError.StatusCode != 404 && apiError.StatusCode != 408 && apiError.StatusCode != 429 {
		return nil, err
	}
	alternate, fallbackErr := s.fallback(ctx, params)
	if fallbackErr != nil {
		return nil, errors.Join(err, fallbackErr)
	}
	return alternate, nil
}

func (s *Session) addChild(child *Session) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return false
	}
	if s.children == nil {
		s.children = map[*Session]struct{}{}
	}
	s.children[child] = struct{}{}
	return true
}
func (s *Session) releaseChild(child *Session) {
	_ = child.Close()
	s.mu.Lock()
	delete(s.children, child)
	s.mu.Unlock()
}
