//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Granularity.
const (
	Daily  Granularity = "daily"
	Hourly Granularity = "hourly"
)

// Valid indicates whether the value is a known member of the Granularity enum.
func (e Granularity) Valid() bool {
	switch e {
	case Daily:
		return true
	case Hourly:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	Degraded HealthStatusStatus = "degraded"
	Ok       HealthStatusStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Modality.
const (
	Llm    Modality = "llm"
	Memory Modality = "memory"
	Phone  Modality = "phone"
	Stt    Modality = "stt"
	Tts    Modality = "tts"
)

// Valid indicates whether the value is a known member of the Modality enum.
func (e Modality) Valid() bool {
	switch e {
	case Llm:
		return true
	case Memory:
		return true
	case Phone:
		return true
	case Stt:
		return true
	case Tts:
		return true
	default:
		return false
	}
}

// Defines values for PhoneCapability.
const (
	Fax   PhoneCapability = "fax"
	Mms   PhoneCapability = "mms"
	Sms   PhoneCapability = "sms"
	Voice PhoneCapability = "voice"
)

// Valid indicates whether the value is a known member of the PhoneCapability enum.
func (e PhoneCapability) Valid() bool {
	switch e {
	case Fax:
		return true
	case Mms:
		return true
	case Sms:
		return true
	case Voice:
		return true
	default:
		return false
	}
}

// Defines values for Tier.
const (
	HighQuality Tier = "high-quality"
	LowLatency  Tier = "low-latency"
)

// Valid indicates whether the value is a known member of the Tier enum.
func (e Tier) Valid() bool {
	switch e {
	case HighQuality:
		return true
	case LowLatency:
		return true
	default:
		return false
	}
}

// AttachNumberRequest defines model for AttachNumberRequest.
type AttachNumberRequest struct {
	// AllowedIps The vendor's signalling addresses, as IPs or CIDR blocks.
	AllowedIps *[]string `json:"allowed_ips,omitempty"`

	// CallId The call every caller joins. Omit to give each caller their own call, named after the number they rang.
	CallId *string `json:"call_id,omitempty"`

	// CallType The Stream call type. Omit for "default".
	CallType *string `json:"call_type,omitempty"`
}

// AttachedNumber defines model for AttachedNumber.
type AttachedNumber struct {
	RouteId string `json:"route_id"`

	// SipUri Where the vendor sends calls, e.g. sip:trunk@sip.stream-io-api.com.
	SipUri  string `json:"sip_uri"`
	TrunkId string `json:"trunk_id"`
}

// AvailableNumber defines model for AvailableNumber.
type AvailableNumber struct {
	Capabilities []PhoneCapability `json:"capabilities"`
	Country      string            `json:"country"`

	// E164 Example: +15125551234
	E164     string  `json:"e164"`
	Locality *string `json:"locality,omitempty"`

	// MonthlyCostMicros Millionths of a dollar per month, zero when the vendor does not quote one.
	MonthlyCostMicros *int64  `json:"monthly_cost_micros,omitempty"`
	Region            *string `json:"region,omitempty"`
}

// BuyNumberRequest defines model for BuyNumberRequest.
type BuyNumberRequest struct {
	// E164 Example: +15125551234
	E164 string `json:"e164"`

	// Tags Cost labels carried onto the purchase's request row.
	Tags *map[string]string `json:"tags,omitempty"`

	// Vendor Example: twilio
	Vendor string `json:"vendor"`
}

// Candidate defines model for Candidate.
type Candidate struct {
	Health   ProviderHealth `json:"health"`
	Model    string         `json:"model"`
	Provider string         `json:"provider"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Granularity defines model for Granularity.
type Granularity string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Dependencies Dependency name to "ok" or a failure description.
	//
	// Example: {"postgres":"ok","redis":"ok"}
	Dependencies map[string]string  `json:"dependencies"`
	Status       HealthStatusStatus `json:"status"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// Modality What kind of work was done. The first three are routed across providers. Memory and phone are recorded but not routed, since there is one memory store and one vendor per number, so the provider paths do not serve them while the statistics paths do.
//
// Example: tts
type Modality string

// PhoneCapability defines model for PhoneCapability.
type PhoneCapability string

// PhoneNumber defines model for PhoneNumber.
type PhoneNumber struct {
	Capabilities      []PhoneCapability `json:"capabilities"`
	Country           string            `json:"country"`
	E164              string            `json:"e164"`
	MonthlyCostMicros int64             `json:"monthly_cost_micros"`
	PurchasedAt       time.Time         `json:"purchased_at"`
	ReleasedAt        *time.Time        `json:"released_at,omitempty"`

	// StreamTrunkId The SIP trunk calls to this number arrive on. Absent until attached.
	StreamTrunkId *string `json:"stream_trunk_id,omitempty"`

	// Tags The customer's own cost labels.
	Tags   *map[string]string `json:"tags,omitempty"`
	Vendor string             `json:"vendor"`
}

// PhoneVendor defines model for PhoneVendor.
type PhoneVendor struct {
	Capabilities []PhoneCapability `json:"capabilities"`

	// Implemented Whether this service can actually work with the vendor.
	Implemented bool `json:"implemented"`

	// MissingCredentials The environment variables the vendor needs and does not have.
	MissingCredentials *[]string `json:"missing_credentials,omitempty"`

	// Ready Implemented and holding every credential it needs.
	Ready bool `json:"ready"`

	// Vendor Example: twilio
	Vendor string `json:"vendor"`
}

// PlaceCallRequest defines model for PlaceCallRequest.
type PlaceCallRequest struct {
	// From One of the customer's own numbers, which is what the person sees.
	From string `json:"from"`

	// SipUri The trunk the answered call joins. Omit to have one created, which is what a one-off call wants.
	SipUri *string            `json:"sip_uri,omitempty"`
	Tags   *map[string]string `json:"tags,omitempty"`
	To     string             `json:"to"`
}

// PlacedCall defines model for PlacedCall.
type PlacedCall struct {
	// Status The vendor's own word for where the call is, e.g. "queued".
	Status       string `json:"status"`
	VendorCallId string `json:"vendor_call_id"`
}

// Provider defines model for Provider.
type Provider struct {
	Health    ProviderHealth `json:"health"`
	Languages []string       `json:"languages"`

	// Model Example: eleven_flash_v2_5
	Model string `json:"model"`

	// Provider Example: elevenlabs
	Provider string `json:"provider"`
	Realtime bool   `json:"realtime"`

	// Tier What the model optimises for.
	Tier Tier `json:"tier"`
}

// ProviderHealth defines model for ProviderHealth.
type ProviderHealth struct {
	// Available False once the error rate crosses the configured threshold.
	Available    bool    `json:"available"`
	ErrorRate    float64 `json:"error_rate"`
	Errors       int64   `json:"errors"`
	LatencyMsAvg float64 `json:"latency_ms_avg"`

	// Requests Requests seen in the current health window.
	Requests int64 `json:"requests"`
}

// RollupRequest defines model for RollupRequest.
type RollupRequest struct {
	From        time.Time    `json:"from"`
	Granularity *Granularity `json:"granularity,omitempty"`
	To          time.Time    `json:"to"`
}

// RollupResult defines model for RollupResult.
type RollupResult struct {
	BucketsWritten int64       `json:"buckets_written"`
	Granularity    Granularity `json:"granularity"`
}

// StatsBucket defines model for StatsBucket.
type StatsBucket struct {
	// AudioMsTotal Billable audio, transcribed or produced.
	AudioMsTotal int64     `json:"audio_ms_total"`
	Bucket       time.Time `json:"bucket"`

	// CachedInputTokensTotal The part of the prompt served from the provider's cache.
	CachedInputTokensTotal int64 `json:"cached_input_tokens_total"`

	// CharactersTotal Billable text. Zero for providers that bill by audio.
	CharactersTotal int64 `json:"characters_total"`

	// CostMicrosTotal Millionths of a dollar, priced from the configured rates.
	CostMicrosTotal int64 `json:"cost_micros_total"`
	ErrorCount      int64 `json:"error_count"`

	// InputTokensTotal Prompt tokens read, cached ones included. Zero outside llm.
	InputTokensTotal int64    `json:"input_tokens_total"`
	LatencyP50Ms     *float64 `json:"latency_p50_ms,omitempty"`
	LatencyP95Ms     *float64 `json:"latency_p95_ms,omitempty"`
	Model            string   `json:"model"`

	// OutputTokensTotal Generated tokens, reasoning included. Zero outside llm.
	OutputTokensTotal int64  `json:"output_tokens_total"`
	Provider          string `json:"provider"`
	RequestCount      int64  `json:"request_count"`

	// Uptime Successes over total requests in the bucket.
	Uptime *float64 `json:"uptime,omitempty"`
}

// TagStatsBucket defines model for TagStatsBucket.
type TagStatsBucket struct {
	AudioMsTotal           int64     `json:"audio_ms_total"`
	Bucket                 time.Time `json:"bucket"`
	CachedInputTokensTotal int64     `json:"cached_input_tokens_total"`
	CharactersTotal        int64     `json:"characters_total"`

	// CostMicrosTotal Millionths of a dollar, priced from the configured rates.
	CostMicrosTotal   int64    `json:"cost_micros_total"`
	ErrorCount        int64    `json:"error_count"`
	InputTokensTotal  int64    `json:"input_tokens_total"`
	LatencyP50Ms      *float64 `json:"latency_p50_ms,omitempty"`
	LatencyP95Ms      *float64 `json:"latency_p95_ms,omitempty"`
	OutputTokensTotal int64    `json:"output_tokens_total"`
	RequestCount      int64    `json:"request_count"`

	// TagKey Example: project
	TagKey string `json:"tag_key"`

	// TagValue Example: moderation
	TagValue string   `json:"tag_value"`
	Uptime   *float64 `json:"uptime,omitempty"`
}

// Tier What the model optimises for.
type Tier string

// TurnStatsBucket defines model for TurnStatsBucket.
type TurnStatsBucket struct {
	AgentId string `json:"agent_id"`

	// AudioOutMsTotal How much speech the agent published in the bucket.
	AudioOutMsTotal float64   `json:"audio_out_ms_total"`
	Bucket          time.Time `json:"bucket"`

	// InterruptedCount Turns a participant talked over before they finished.
	InterruptedCount int64    `json:"interrupted_count"`
	LlmTtftP50Ms     *float64 `json:"llm_ttft_p50_ms,omitempty"`
	LlmTtftP95Ms     *float64 `json:"llm_ttft_p95_ms,omitempty"`

	// RoundtripP50Ms Settled transcript to first audio published.
	RoundtripP50Ms  *float64 `json:"roundtrip_p50_ms,omitempty"`
	RoundtripP95Ms  *float64 `json:"roundtrip_p95_ms,omitempty"`
	RoundtripP99Ms  *float64 `json:"roundtrip_p99_ms,omitempty"`
	SttLatencyP50Ms *float64 `json:"stt_latency_p50_ms,omitempty"`
	SttLatencyP95Ms *float64 `json:"stt_latency_p95_ms,omitempty"`
	TtsTtfbP50Ms    *float64 `json:"tts_ttfb_p50_ms,omitempty"`
	TtsTtfbP95Ms    *float64 `json:"tts_ttfb_p95_ms,omitempty"`
	TurnCount       int64    `json:"turn_count"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListPhoneNumbersParams defines parameters for ListPhoneNumbers.
type ListPhoneNumbersParams struct {
	// IncludeReleased Include numbers that have been given back. A released number keeps its row, because what it cost while it was held is still part of that month's bill.
	IncludeReleased *bool `form:"include_released,omitempty" json:"include_released,omitempty"`
}

// SearchPhoneNumbersParams defines parameters for SearchPhoneNumbers.
type SearchPhoneNumbersParams struct {
	Vendor string `form:"vendor" json:"vendor"`

	// Country ISO 3166-1 alpha-2 country code.
	Country  string  `form:"country" json:"country"`
	AreaCode *string `form:"area_code,omitempty" json:"area_code,omitempty"`

	// Contains Digits the number must contain.
	Contains *string `form:"contains,omitempty" json:"contains,omitempty"`
	Limit    *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTurnStatsParams defines parameters for GetTurnStats.
type GetTurnStatsParams struct {
	// AgentId Narrow to one agent. Omit for every agent the customer runs.
	AgentId     *string      `form:"agent_id,omitempty" json:"agent_id,omitempty"`
	Granularity *Granularity `form:"granularity,omitempty" json:"granularity,omitempty"`

	// From Start of the window, inclusive.
	From time.Time `form:"from" json:"from"`

	// To End of the window, exclusive.
	To time.Time `form:"to" json:"to"`
}

// ResolveTargetParams defines parameters for ResolveTarget.
type ResolveTargetParams struct {
	// Language Language hints that candidates must cover. Repeat for several.
	Language *[]string `form:"language,omitempty" json:"language,omitempty"`
}

// GetStatsParams defines parameters for GetStats.
type GetStatsParams struct {
	Granularity *Granularity `form:"granularity,omitempty" json:"granularity,omitempty"`

	// From Start of the window, inclusive.
	From time.Time `form:"from" json:"from"`

	// To End of the window, exclusive.
	To time.Time `form:"to" json:"to"`

	// Tag Only count requests carrying every one of these cost labels, each written "key:value". Repeat for several. Filtering reads the request rows rather than the rollups, since a rollup bucket no longer knows which labels its requests carried.
	Tag *[]string `form:"tag,omitempty" json:"tag,omitempty"`
}

// GetTagStatsParams defines parameters for GetTagStats.
type GetTagStatsParams struct {
	// Key The cost label to group by.
	Key         string       `form:"key" json:"key"`
	Granularity *Granularity `form:"granularity,omitempty" json:"granularity,omitempty"`

	// From Start of the window, inclusive.
	From time.Time `form:"from" json:"from"`

	// To End of the window, exclusive.
	To time.Time `form:"to" json:"to"`
}

// PlacePhoneCallJSONRequestBody defines body for PlacePhoneCall for application/json ContentType.
type PlacePhoneCallJSONRequestBody = PlaceCallRequest

// BuyPhoneNumberJSONRequestBody defines body for BuyPhoneNumber for application/json ContentType.
type BuyPhoneNumberJSONRequestBody = BuyNumberRequest

// AttachPhoneNumberJSONRequestBody defines body for AttachPhoneNumber for application/json ContentType.
type AttachPhoneNumberJSONRequestBody = AttachNumberRequest

// RunRollupJSONRequestBody defines body for RunRollup for application/json ContentType.
type RunRollupJSONRequestBody = RollupRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetHealth Liveness and dependency check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// PlacePhoneCall Place an outbound call and bridge it into a Stream call
	// (POST /v1/phone/calls)
	PlacePhoneCall(w http.ResponseWriter, r *http.Request)
	// ListPhoneNumbers The numbers the calling customer holds
	// (GET /v1/phone/numbers)
	ListPhoneNumbers(w http.ResponseWriter, r *http.Request, params ListPhoneNumbersParams)
	// BuyPhoneNumber Buy a number, which starts its monthly charge
	// (POST /v1/phone/numbers)
	BuyPhoneNumber(w http.ResponseWriter, r *http.Request)
	// SearchPhoneNumbers Search a vendor for numbers to buy
	// (GET /v1/phone/numbers/available)
	SearchPhoneNumbers(w http.ResponseWriter, r *http.Request, params SearchPhoneNumbersParams)
	// ReleasePhoneNumber Give a number back, which stops its monthly charge
	// (DELETE /v1/phone/numbers/{e164})
	ReleasePhoneNumber(w http.ResponseWriter, r *http.Request, e164 string)
	// AttachPhoneNumber Point a number at a Stream call
	// (POST /v1/phone/numbers/{e164}/attach)
	AttachPhoneNumber(w http.ResponseWriter, r *http.Request, e164 string)
	// ListPhoneVendors List the telephony vendors and whether they can be used
	// (GET /v1/phone/vendors)
	ListPhoneVendors(w http.ResponseWriter, r *http.Request)
	// RunRollup Aggregate request rows into a rollup table
	// (POST /v1/stats/rollup)
	RunRollup(w http.ResponseWriter, r *http.Request)
	// GetTurnStats Conversational latency for the calling customer
	// (GET /v1/turns/stats)
	GetTurnStats(w http.ResponseWriter, r *http.Request, params GetTurnStatsParams)
	// ListProviders List the providers configured for a modality and their live health
	// (GET /v1/{modality}/providers)
	ListProviders(w http.ResponseWriter, r *http.Request, modality Modality)
	// ResolveTarget Resolve a provider name or capability shortcut to a ranked candidate list
	// (GET /v1/{modality}/routes/{target})
	ResolveTarget(w http.ResponseWriter, r *http.Request, modality Modality, target string, params ResolveTargetParams)
	// GetStats Aggregated usage for the calling customer
	// (GET /v1/{modality}/stats)
	GetStats(w http.ResponseWriter, r *http.Request, modality Modality, params GetStatsParams)
	// GetTagStats Aggregated usage broken down by the values of one cost label
	// (GET /v1/{modality}/stats/tags)
	GetTagStats(w http.ResponseWriter, r *http.Request, modality Modality, params GetTagStatsParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlacePhoneCall operation middleware
func (siw *ServerInterfaceWrapper) PlacePhoneCall(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlacePhoneCall(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPhoneNumbers operation middleware
func (siw *ServerInterfaceWrapper) ListPhoneNumbers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPhoneNumbersParams

	// ------------- Optional query parameter "include_released" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_released", r.URL.Query(), &params.IncludeReleased, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "include_released"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_released", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPhoneNumbers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BuyPhoneNumber operation middleware
func (siw *ServerInterfaceWrapper) BuyPhoneNumber(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BuyPhoneNumber(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPhoneNumbers operation middleware
func (siw *ServerInterfaceWrapper) SearchPhoneNumbers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPhoneNumbersParams

	// ------------- Required query parameter "vendor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "vendor", r.URL.Query(), &params.Vendor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "vendor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vendor", Err: err})
		}
		return
	}

	// ------------- Required query parameter "country" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "country", r.URL.Query(), &params.Country, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "country"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "country", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "area_code" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "area_code", r.URL.Query(), &params.AreaCode, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "area_code"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "area_code", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "contains" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "contains", r.URL.Query(), &params.Contains, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "contains"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "contains", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPhoneNumbers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReleasePhoneNumber operation middleware
func (siw *ServerInterfaceWrapper) ReleasePhoneNumber(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "e164" -------------
	var e164 string

	err = runtime.BindStyledParameterWithOptions("simple", "e164", r.PathValue("e164"), &e164, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "e164", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReleasePhoneNumber(w, r, e164)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AttachPhoneNumber operation middleware
func (siw *ServerInterfaceWrapper) AttachPhoneNumber(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "e164" -------------
	var e164 string

	err = runtime.BindStyledParameterWithOptions("simple", "e164", r.PathValue("e164"), &e164, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "e164", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AttachPhoneNumber(w, r, e164)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPhoneVendors operation middleware
func (siw *ServerInterfaceWrapper) ListPhoneVendors(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPhoneVendors(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunRollup operation middleware
func (siw *ServerInterfaceWrapper) RunRollup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunRollup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTurnStats operation middleware
func (siw *ServerInterfaceWrapper) GetTurnStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTurnStatsParams

	// ------------- Optional query parameter "agent_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "agent_id", r.URL.Query(), &params.AgentId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "agent_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "agent_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "granularity", r.URL.Query(), &params.Granularity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "granularity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		}
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTurnStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProviders operation middleware
func (siw *ServerInterfaceWrapper) ListProviders(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "modality" -------------
	var modality Modality

	err = runtime.BindStyledParameterWithOptions("simple", "modality", r.PathValue("modality"), &modality, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProviders(w, r, modality)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResolveTarget operation middleware
func (siw *ServerInterfaceWrapper) ResolveTarget(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "modality" -------------
	var modality Modality

	err = runtime.BindStyledParameterWithOptions("simple", "modality", r.PathValue("modality"), &modality, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modality", Err: err})
		return
	}

	// ------------- Path parameter "target" -------------
	var target string

	err = runtime.BindStyledParameterWithOptions("simple", "target", r.PathValue("target"), &target, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "target", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResolveTargetParams

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "language"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResolveTarget(w, r, modality, target, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStats operation middleware
func (siw *ServerInterfaceWrapper) GetStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "modality" -------------
	var modality Modality

	err = runtime.BindStyledParameterWithOptions("simple", "modality", r.PathValue("modality"), &modality, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modality", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetStatsParams

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "granularity", r.URL.Query(), &params.Granularity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "granularity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		}
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStats(w, r, modality, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTagStats operation middleware
func (siw *ServerInterfaceWrapper) GetTagStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "modality" -------------
	var modality Modality

	err = runtime.BindStyledParameterWithOptions("simple", "modality", r.PathValue("modality"), &modality, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "modality", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTagStatsParams

	// ------------- Required query parameter "key" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "key", r.URL.Query(), &params.Key, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "key"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "granularity" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "granularity", r.URL.Query(), &params.Granularity, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "granularity"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "granularity", Err: err})
		}
		return
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTagStats(w, r, modality, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/{modality}/providers", wrapper.ListProviders)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/{modality}/routes/{target}", wrapper.ResolveTarget)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/{modality}/stats", wrapper.GetStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/{modality}/stats/tags", wrapper.GetTagStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/turns/stats", wrapper.GetTurnStats)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/phone/vendors", wrapper.ListPhoneVendors)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/phone/numbers/available", wrapper.SearchPhoneNumbers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/phone/numbers", wrapper.ListPhoneNumbers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/phone/numbers", wrapper.BuyPhoneNumber)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/v1/phone/numbers/{e164}", wrapper.ReleasePhoneNumber)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/phone/numbers/{e164}/attach", wrapper.AttachPhoneNumber)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/phone/calls", wrapper.PlacePhoneCall)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/stats/rollup", wrapper.RunRollup)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthStatus

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse HealthStatus

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePhoneCallRequestObject struct {
	Body *PlacePhoneCallJSONRequestBody
}

type PlacePhoneCallResponseObject interface {
	VisitPlacePhoneCallResponse(w http.ResponseWriter) error
}

type PlacePhoneCall202JSONResponse PlacedCall

func (response PlacePhoneCall202JSONResponse) VisitPlacePhoneCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePhoneCall400JSONResponse struct{ BadRequestJSONResponse }

func (response PlacePhoneCall400JSONResponse) VisitPlacePhoneCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePhoneCall401JSONResponse struct{ UnauthorizedJSONResponse }

func (response PlacePhoneCall401JSONResponse) VisitPlacePhoneCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PlacePhoneCall404JSONResponse struct{ NotFoundJSONResponse }

func (response PlacePhoneCall404JSONResponse) VisitPlacePhoneCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListPhoneNumbersRequestObject struct {
	Params ListPhoneNumbersParams
}

type ListPhoneNumbersResponseObject interface {
	VisitListPhoneNumbersResponse(w http.ResponseWriter) error
}

type ListPhoneNumbers200JSONResponse []PhoneNumber

func (response ListPhoneNumbers200JSONResponse) VisitListPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPhoneNumbers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListPhoneNumbers400JSONResponse) VisitListPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListPhoneNumbers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPhoneNumbers401JSONResponse) VisitListPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type BuyPhoneNumberRequestObject struct {
	Body *BuyPhoneNumberJSONRequestBody
}

type BuyPhoneNumberResponseObject interface {
	VisitBuyPhoneNumberResponse(w http.ResponseWriter) error
}

type BuyPhoneNumber201JSONResponse PhoneNumber

func (response BuyPhoneNumber201JSONResponse) VisitBuyPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type BuyPhoneNumber400JSONResponse struct{ BadRequestJSONResponse }

func (response BuyPhoneNumber400JSONResponse) VisitBuyPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type BuyPhoneNumber401JSONResponse struct{ UnauthorizedJSONResponse }

func (response BuyPhoneNumber401JSONResponse) VisitBuyPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type BuyPhoneNumber404JSONResponse struct{ NotFoundJSONResponse }

func (response BuyPhoneNumber404JSONResponse) VisitBuyPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPhoneNumbersRequestObject struct {
	Params SearchPhoneNumbersParams
}

type SearchPhoneNumbersResponseObject interface {
	VisitSearchPhoneNumbersResponse(w http.ResponseWriter) error
}

type SearchPhoneNumbers200JSONResponse []AvailableNumber

func (response SearchPhoneNumbers200JSONResponse) VisitSearchPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPhoneNumbers400JSONResponse struct{ BadRequestJSONResponse }

func (response SearchPhoneNumbers400JSONResponse) VisitSearchPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPhoneNumbers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SearchPhoneNumbers401JSONResponse) VisitSearchPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SearchPhoneNumbers404JSONResponse struct{ NotFoundJSONResponse }

func (response SearchPhoneNumbers404JSONResponse) VisitSearchPhoneNumbersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReleasePhoneNumberRequestObject struct {
	E164 string `json:"e164"`
}

type ReleasePhoneNumberResponseObject interface {
	VisitReleasePhoneNumberResponse(w http.ResponseWriter) error
}

type ReleasePhoneNumber204Response struct {
}

func (response ReleasePhoneNumber204Response) VisitReleasePhoneNumberResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ReleasePhoneNumber400JSONResponse struct{ BadRequestJSONResponse }

func (response ReleasePhoneNumber400JSONResponse) VisitReleasePhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReleasePhoneNumber401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReleasePhoneNumber401JSONResponse) VisitReleasePhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReleasePhoneNumber404JSONResponse struct{ NotFoundJSONResponse }

func (response ReleasePhoneNumber404JSONResponse) VisitReleasePhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type AttachPhoneNumberRequestObject struct {
	E164 string `json:"e164"`
	Body *AttachPhoneNumberJSONRequestBody
}

type AttachPhoneNumberResponseObject interface {
	VisitAttachPhoneNumberResponse(w http.ResponseWriter) error
}

type AttachPhoneNumber200JSONResponse AttachedNumber

func (response AttachPhoneNumber200JSONResponse) VisitAttachPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AttachPhoneNumber400JSONResponse struct{ BadRequestJSONResponse }

func (response AttachPhoneNumber400JSONResponse) VisitAttachPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type AttachPhoneNumber401JSONResponse struct{ UnauthorizedJSONResponse }

func (response AttachPhoneNumber401JSONResponse) VisitAttachPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type AttachPhoneNumber404JSONResponse struct{ NotFoundJSONResponse }

func (response AttachPhoneNumber404JSONResponse) VisitAttachPhoneNumberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListPhoneVendorsRequestObject struct {
}

type ListPhoneVendorsResponseObject interface {
	VisitListPhoneVendorsResponse(w http.ResponseWriter) error
}

type ListPhoneVendors200JSONResponse []PhoneVendor

func (response ListPhoneVendors200JSONResponse) VisitListPhoneVendorsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPhoneVendors401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListPhoneVendors401JSONResponse) VisitListPhoneVendorsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RunRollupRequestObject struct {
	Body *RunRollupJSONRequestBody
}

type RunRollupResponseObject interface {
	VisitRunRollupResponse(w http.ResponseWriter) error
}

type RunRollup200JSONResponse RollupResult

func (response RunRollup200JSONResponse) VisitRunRollupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RunRollup400JSONResponse struct{ BadRequestJSONResponse }

func (response RunRollup400JSONResponse) VisitRunRollupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RunRollup401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RunRollup401JSONResponse) VisitRunRollupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurnStatsRequestObject struct {
	Params GetTurnStatsParams
}

type GetTurnStatsResponseObject interface {
	VisitGetTurnStatsResponse(w http.ResponseWriter) error
}

type GetTurnStats200JSONResponse []TurnStatsBucket

func (response GetTurnStats200JSONResponse) VisitGetTurnStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurnStats400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTurnStats400JSONResponse) VisitGetTurnStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTurnStats401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTurnStats401JSONResponse) VisitGetTurnStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProvidersRequestObject struct {
	Modality Modality `json:"modality"`
}

type ListProvidersResponseObject interface {
	VisitListProvidersResponse(w http.ResponseWriter) error
}

type ListProviders200JSONResponse []Provider

func (response ListProviders200JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProviders401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListProviders401JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProviders404JSONResponse struct{ NotFoundJSONResponse }

func (response ListProviders404JSONResponse) VisitListProvidersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveTargetRequestObject struct {
	Modality Modality `json:"modality"`
	Target   string   `json:"target"`
	Params   ResolveTargetParams
}

type ResolveTargetResponseObject interface {
	VisitResolveTargetResponse(w http.ResponseWriter) error
}

type ResolveTarget200JSONResponse []Candidate

func (response ResolveTarget200JSONResponse) VisitResolveTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveTarget401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ResolveTarget401JSONResponse) VisitResolveTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ResolveTarget404JSONResponse struct{ NotFoundJSONResponse }

func (response ResolveTarget404JSONResponse) VisitResolveTargetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetStatsRequestObject struct {
	Modality Modality `json:"modality"`
	Params   GetStatsParams
}

type GetStatsResponseObject interface {
	VisitGetStatsResponse(w http.ResponseWriter) error
}

type GetStats200JSONResponse []StatsBucket

func (response GetStats200JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetStats400JSONResponse struct{ BadRequestJSONResponse }

func (response GetStats400JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetStats401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetStats401JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetStats404JSONResponse struct{ NotFoundJSONResponse }

func (response GetStats404JSONResponse) VisitGetStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTagStatsRequestObject struct {
	Modality Modality `json:"modality"`
	Params   GetTagStatsParams
}

type GetTagStatsResponseObject interface {
	VisitGetTagStatsResponse(w http.ResponseWriter) error
}

type GetTagStats200JSONResponse []TagStatsBucket

func (response GetTagStats200JSONResponse) VisitGetTagStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTagStats400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTagStats400JSONResponse) VisitGetTagStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTagStats401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTagStats401JSONResponse) VisitGetTagStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTagStats404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTagStats404JSONResponse) VisitGetTagStatsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetHealth Liveness and dependency check
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// PlacePhoneCall Place an outbound call and bridge it into a Stream call
	// (POST /v1/phone/calls)
	PlacePhoneCall(ctx context.Context, request PlacePhoneCallRequestObject) (PlacePhoneCallResponseObject, error)
	// ListPhoneNumbers The numbers the calling customer holds
	// (GET /v1/phone/numbers)
	ListPhoneNumbers(ctx context.Context, request ListPhoneNumbersRequestObject) (ListPhoneNumbersResponseObject, error)
	// BuyPhoneNumber Buy a number, which starts its monthly charge
	// (POST /v1/phone/numbers)
	BuyPhoneNumber(ctx context.Context, request BuyPhoneNumberRequestObject) (BuyPhoneNumberResponseObject, error)
	// SearchPhoneNumbers Search a vendor for numbers to buy
	// (GET /v1/phone/numbers/available)
	SearchPhoneNumbers(ctx context.Context, request SearchPhoneNumbersRequestObject) (SearchPhoneNumbersResponseObject, error)
	// ReleasePhoneNumber Give a number back, which stops its monthly charge
	// (DELETE /v1/phone/numbers/{e164})
	ReleasePhoneNumber(ctx context.Context, request ReleasePhoneNumberRequestObject) (ReleasePhoneNumberResponseObject, error)
	// AttachPhoneNumber Point a number at a Stream call
	// (POST /v1/phone/numbers/{e164}/attach)
	AttachPhoneNumber(ctx context.Context, request AttachPhoneNumberRequestObject) (AttachPhoneNumberResponseObject, error)
	// ListPhoneVendors List the telephony vendors and whether they can be used
	// (GET /v1/phone/vendors)
	ListPhoneVendors(ctx context.Context, request ListPhoneVendorsRequestObject) (ListPhoneVendorsResponseObject, error)
	// RunRollup Aggregate request rows into a rollup table
	// (POST /v1/stats/rollup)
	RunRollup(ctx context.Context, request RunRollupRequestObject) (RunRollupResponseObject, error)
	// GetTurnStats Conversational latency for the calling customer
	// (GET /v1/turns/stats)
	GetTurnStats(ctx context.Context, request GetTurnStatsRequestObject) (GetTurnStatsResponseObject, error)
	// ListProviders List the providers configured for a modality and their live health
	// (GET /v1/{modality}/providers)
	ListProviders(ctx context.Context, request ListProvidersRequestObject) (ListProvidersResponseObject, error)
	// ResolveTarget Resolve a provider name or capability shortcut to a ranked candidate list
	// (GET /v1/{modality}/routes/{target})
	ResolveTarget(ctx context.Context, request ResolveTargetRequestObject) (ResolveTargetResponseObject, error)
	// GetStats Aggregated usage for the calling customer
	// (GET /v1/{modality}/stats)
	GetStats(ctx context.Context, request GetStatsRequestObject) (GetStatsResponseObject, error)
	// GetTagStats Aggregated usage broken down by the values of one cost label
	// (GET /v1/{modality}/stats/tags)
	GetTagStats(ctx context.Context, request GetTagStatsRequestObject) (GetTagStatsResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PlacePhoneCall operation middleware
func (sh *strictHandler) PlacePhoneCall(w http.ResponseWriter, r *http.Request) {
	var request PlacePhoneCallRequestObject

	var body PlacePhoneCallJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PlacePhoneCall(ctx, request.(PlacePhoneCallRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PlacePhoneCall")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PlacePhoneCallResponseObject); ok {
		if err := validResponse.VisitPlacePhoneCallResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPhoneNumbers operation middleware
func (sh *strictHandler) ListPhoneNumbers(w http.ResponseWriter, r *http.Request, params ListPhoneNumbersParams) {
	var request ListPhoneNumbersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPhoneNumbers(ctx, request.(ListPhoneNumbersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPhoneNumbers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPhoneNumbersResponseObject); ok {
		if err := validResponse.VisitListPhoneNumbersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BuyPhoneNumber operation middleware
func (sh *strictHandler) BuyPhoneNumber(w http.ResponseWriter, r *http.Request) {
	var request BuyPhoneNumberRequestObject

	var body BuyPhoneNumberJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BuyPhoneNumber(ctx, request.(BuyPhoneNumberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BuyPhoneNumber")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BuyPhoneNumberResponseObject); ok {
		if err := validResponse.VisitBuyPhoneNumberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchPhoneNumbers operation middleware
func (sh *strictHandler) SearchPhoneNumbers(w http.ResponseWriter, r *http.Request, params SearchPhoneNumbersParams) {
	var request SearchPhoneNumbersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchPhoneNumbers(ctx, request.(SearchPhoneNumbersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchPhoneNumbers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchPhoneNumbersResponseObject); ok {
		if err := validResponse.VisitSearchPhoneNumbersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReleasePhoneNumber operation middleware
func (sh *strictHandler) ReleasePhoneNumber(w http.ResponseWriter, r *http.Request, e164 string) {
	var request ReleasePhoneNumberRequestObject

	request.E164 = e164

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReleasePhoneNumber(ctx, request.(ReleasePhoneNumberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReleasePhoneNumber")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReleasePhoneNumberResponseObject); ok {
		if err := validResponse.VisitReleasePhoneNumberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AttachPhoneNumber operation middleware
func (sh *strictHandler) AttachPhoneNumber(w http.ResponseWriter, r *http.Request, e164 string) {
	var request AttachPhoneNumberRequestObject

	request.E164 = e164

	var body AttachPhoneNumberJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AttachPhoneNumber(ctx, request.(AttachPhoneNumberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AttachPhoneNumber")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AttachPhoneNumberResponseObject); ok {
		if err := validResponse.VisitAttachPhoneNumberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPhoneVendors operation middleware
func (sh *strictHandler) ListPhoneVendors(w http.ResponseWriter, r *http.Request) {
	var request ListPhoneVendorsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPhoneVendors(ctx, request.(ListPhoneVendorsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPhoneVendors")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPhoneVendorsResponseObject); ok {
		if err := validResponse.VisitListPhoneVendorsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunRollup operation middleware
func (sh *strictHandler) RunRollup(w http.ResponseWriter, r *http.Request) {
	var request RunRollupRequestObject

	var body RunRollupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunRollup(ctx, request.(RunRollupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunRollup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunRollupResponseObject); ok {
		if err := validResponse.VisitRunRollupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTurnStats operation middleware
func (sh *strictHandler) GetTurnStats(w http.ResponseWriter, r *http.Request, params GetTurnStatsParams) {
	var request GetTurnStatsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTurnStats(ctx, request.(GetTurnStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTurnStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTurnStatsResponseObject); ok {
		if err := validResponse.VisitGetTurnStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProviders operation middleware
func (sh *strictHandler) ListProviders(w http.ResponseWriter, r *http.Request, modality Modality) {
	var request ListProvidersRequestObject

	request.Modality = modality

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListProviders(ctx, request.(ListProvidersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProviders")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListProvidersResponseObject); ok {
		if err := validResponse.VisitListProvidersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResolveTarget operation middleware
func (sh *strictHandler) ResolveTarget(w http.ResponseWriter, r *http.Request, modality Modality, target string, params ResolveTargetParams) {
	var request ResolveTargetRequestObject

	request.Modality = modality
	request.Target = target
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResolveTarget(ctx, request.(ResolveTargetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResolveTarget")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResolveTargetResponseObject); ok {
		if err := validResponse.VisitResolveTargetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStats operation middleware
func (sh *strictHandler) GetStats(w http.ResponseWriter, r *http.Request, modality Modality, params GetStatsParams) {
	var request GetStatsRequestObject

	request.Modality = modality
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetStats(ctx, request.(GetStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetStatsResponseObject); ok {
		if err := validResponse.VisitGetStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTagStats operation middleware
func (sh *strictHandler) GetTagStats(w http.ResponseWriter, r *http.Request, modality Modality, params GetTagStatsParams) {
	var request GetTagStatsRequestObject

	request.Modality = modality
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTagStats(ctx, request.(GetTagStatsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTagStats")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTagStatsResponseObject); ok {
		if err := validResponse.VisitGetTagStatsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fx7bxs5kv8qRN8B+WNl2c7rdrw44JLMTja4mUyQZPcOFwcC1SypOWKTHZItRRv4ux+qyH6pKUuOHc8G",
	"u/8EjsRmF+vxqyf1JctNWRkN2rvs4ktWcctL8GDpf78YwZX0W/xbgMutrLw0OrvI/qeQecFWUgtmFqw0",
	"AhTzhllTe5hmk0zioor7IptkmpeQXWRls9kks/CplhZEduFtDZPM5QWUHN/y7xYW2UX2b6cdWafhW3fa",
	"UnN1dYV7uMpoB0Tocy7ewqcanMf/5UZ70PQnryolc45Un/7mkPQvR77tz9YaG141PPr7ApgNL2Mb7ljJ",
	"1cLYEkR2NcleG/+TqbX49mS8NszVecEatk5YZc1aCrDMWOYKY31ee6Tpr5rXvjBW/h3E/bAnr503JVhW",
	"AEeCpGOldE7qZYYPxD3wFc+853nxui7nYHsSrKypwHoZpMuVMhsQM1m5sSbi+9aghbEPHHNyqblSUi8Z",
	"F8KCc+AmjDv26o1Dtrx49eNbNlcmXznSUg8lbem3Faqo85ZonDQfcGv5Fv+fc6VmUqRfj18yWIPd0p9g",
	"2W9Gajdlv5bSo1ks5RoY8LxovvcFSMvMRtMHE4YmIhhf+PAd08QQ/HPLLNfL6aXOJmMqiarwaYqud94C",
	"LwN5uCoStDCWXWYCFrxW/jKbjnfuGGDmv0FOWhQkBSLIaiwkMv3IohGhTlaz2soUjoAFOnKQIXOghSOS",
	"3YTBdDllTlYIE3r1X05WU0dnOpHmhFdymptymmIMrU8Tc9WHnw/dykl3go7ejylGrLlUfK5gHydyXvG5",
	"VLL5f6tl19nTm8JoeNE8uU3qoKm1t9skg+H86WP8Aj7zslL43R/On5w/fPLkyfnDR49TLFImb7F99GVp",
	"tC/UdpYb52elzK1JWN4vUimJCx36AM6EUYpbVoFl9PyE/R2sYZsCdF/CwoBj2nj2qTYemNHkMBBCuc8u",
	"Mqn90x7BUntYgs1IbEsZIOp6kRIvOnZNhgJJifR5vT0AQTfnr+fLAF5CSGQYV28GO44eGDL3hXGeKT4H",
	"hdZgrQTBjPaGOFnVNi+4gweu9UTWbHqW0B0tMH1Iut9IJU3S7Pt8jI9G5Urx7QXXQgruYcywArjyxUGt",
	"jy7rL2E1aZ4AleRP494OK0C7stlu0pCTOkTwZGOJNx8fUDZaltr3peW6Vty28RPhbXaRFaa2CvUSdF3i",
	"Hu0Hgku17W3WHT4w6J3nvnZjWgVUoAXovHGYX6dzPzbbbMkhoee6zMzqMkPXydmCS1VbYL2HUOVavfqS",
	"Vcb5pcV3ZWZFcZ6Q8T8pl+La4zScoKcELC0XIBKM2GF+3GAyZEBKGNdFsty3gezG2BUFdQJhiaETXUjr",
	"PPOFBWDcQghxBeOIia6NudyU/QKlsVvGtWAVgnlYDbmxAgSb155ALzw+YU7qnByfBQyPcH0ZNnDeWKBt",
	"8MMImgiqISiYMBdBoAn3MMxGiml/B3ZN+5ZsU0gVfCvySTovc9cuDhFFw3fnPcKBR14qVaLhEDHZJKOz",
	"IE97+EHrRsq068J6cl0bmQP61RKfLOnfBf+cVHXa5h/Rtx7rJY9wZQ2Aixn3g0cQTE+8LCHFYAsKDj2k",
	"a0XBSZNajUMxCqBm/QgpETm+esNoRYjEGPkd6Zq4FP3RGl33lD2bO9Ce1dpLxXiMEaffwCH284oHLsTO",
	"nY884PuOChhaf7cnckgLfEeYKfAh/ftbS8z9aLREYy1BexDJsBuhJwgVIUPmmMZoxnNfc6W2EQmlL3qh",
	"W4/Jc2MUcE1WEDK7WW5BgPaSqz1ZGui1tEYjTWzNrUQ1df3IUAMIR8jXxogFX8PNMjULXCRg/lXHDnpD",
	"YZTANDGmbS3tTPpAR/qwdxFO9SXT0HtEkPpG8RxecKX2BqkLa8rxyX/VgK7Nj+0nWLOboKfIC3RDG3SG",
	"5FzAOqOZA3BJY96b0KGgA3LgNly7DVgQIQfdyYpRtuTjcgucnOKQDo5fnpjFIjy94dq7PYnwjbFlxF1v",
	"DuME8ZeW7pWPQAGNJdNFOtcUL1AkG2MFJeibNjGmw8smG77MPtVQg0jm7Y1+znrlimOUsl3fxmTJA/YC",
	"8LsJ9hXXy5ovd4DvoIm3OUJng6BgDXq2UNwVs/XD2ZMUc/oZxO6jis9d2udyRa61I6wHB16G3a479ntc",
	"c0SK0jGj99b4imsTmB2+jstnTcFirH8/ceXQBkMoyiiZYZZ7tEnjXITn3OiFXNZoxxgHO8TONDzSBjMb",
	"M8IuQDE1vr59IgBP+8CxUZPiHpOTWelmfL088g0xQU4YX8RRdICgmdQRIq1FBxX4zTZSi5BZH6RvR8Id",
	"13s0tAcesGp0spSU3xql6uog9h8XSS6Huel16ttPY1ucPOYtNwLP5nSOUuTdw83rfAXezTZWeg/6SHX5",
	"2kPuEN7fZjIiJXUYTNPdc1qYsMZaSIOC9sZzNdbK5zIE8IwWTpi3XOP3cxCYhlfWiDoPIfYRPJi3VByn",
	"GDnF7zOpq9rPvFmB3kso+q6KW98EF5U1ZRUTUMFQ3IM09YFjtPmRhOcFtzz3YA8zysNnP2X/B9aQ52xT",
	"cuYxiphLpdh8G9h57Mu7+H7f29PFzwmrrMz7x+9hJ9q6O5KCgA6UiByp7ceI7E0QUVjEMPKcBKFQrcEx",
	"qXNVCxCRm6b2TgpgSpVHkt3gWPXkbFa6NELvyVA7xG43+eHJ12+yv45oan+YUy9BA8pLRGZNkFvOaEwZ",
	"bs2layqZra+4kezrqglRhqd4V+c59cCYWWO2h2dtKsau8XgBIgakH8vmw0FNxJ/JLuwlDDypwtchUlqU",
	"Kevd5erQvlIQ/p4vb4ji9w3GX4mh/1To910h1h5cOqoxdnPI8Hw5W8F2mApV1pABpDPs2ZqrGoZPoJ1b",
	"mh9IPdTh0m2hpSG3T8h3jC4xbUx0ItBqwjiNQeZJBO9FKL01xXRlNidR4zAxlMvi5FMduhupevr72urr",
	"sWwJ2u/r3AfOmtpfE7L+xWxYWecFcxVAHiqGtCmr6rmSDuOLI5zNyCJuipeo3tbWlQfR2cJO0Fpb7Rin",
	"wFXmsuLaM8/VCiMgdJFzWJhQd9myhdRE+7Gxjypn3i/8LaGk3eU2WGJNrYW3suoRsxMagPcKw5uYXlBY",
	"GJtdJPNOdl8VGgxouKOj/PDD12/jvJ/dCdYPNrrNwbx3KOn57cjpdrkVLbXVN3Afu6WOBkB6iNzbMWWY",
	"SWAZQyXyG/Iac+93mKoHwHoRy9ivUt0rWzsM29sRNEmF/YUEO2V/pmJ/2w1l0rEVbEFgfih9O7cYpta6",
	"ycX/PWneePJKdOzglfxviNOIUi9MosJkag8uwuKJNyeYqlL7Af/ADxrEtHyxkPmoq0xrLVTG+lgUl57a",
	"Xs1ZKu6pYO5yU4VzdPOAsU/seNlrFlOzRy+Z35hmqcTMz8XXUCrIHFQcAza1DU3wOLYmXcdOehlnPvJ7",
	"wKM49/cnTJoU47Uv8KEwZ4ibaON7pQPp2Bqsk0bH6r70FFv8Qm6QeGipPUdrsovsbPpwekYhUwWaVzK7",
	"yB5Nz6aPsgmNnJKOnHY16WXwIejyiAJUm+wl+Fgv3RklfXh2dmdDkoOpjX2jpHQ+1vThgid7cvbo3oh4",
	"xkQ39yEdq3VXuuwbYHbx4eMkc3VZcrvNLrKf5Ro0uNiw67bIC8hX9OTp+vyUxgdOqYvcTIgknBH1pB84",
	"6jujkuk5oj4zWnV6HJuExsql1JhMdN0RpCA3WkOOaS15Mt7vQlEsIh3jirptzOgJ5iOhA8p1MygpZJwd",
	"NbUPqjjUGerwxNar6sV9z03oON6JuEZtvqsh3CKCX4109uHdvj+0sfZobBSEdKxSPCcwiYJA1X0c7Cf1",
	"ipbm0968Nj1yfviRwRQzPfT48EPtODYpcqu6dEbGNQo6aFqrRnMrxRJQiaQmNeoN0e4odWyf7oWYn6Xz",
	"vWEWGhXojdd/GLWoQ12pacuG8iU1SecAmoaINZvzfDVlz1gzC9KMZKwAKtR9x6zZTNgccl47GPiMOBAk",
	"w9h6AUoQ6nipVA+NuQ/Tmw8clU6DHZBb/FQDDUVErxjLYLOGkqw/x99Ouy24cjBuFV19vCXsHj8m8bqL",
	"cgZ9xKtDIyZte1zDBpwPwfH9qfhAY98Xfb0I1oaW103aGyUcFRcjwg518Xm97TPj20DXaIz2KOg6vzvo",
	"6os7Ld5oLdKxuamXhY8BVhjS+17g63mNkVczDhiGJpzn1gcAiFNKLC+4XUIatE4HTeEkfL0DbvPiegBL",
	"DMGkoKIdfdl/8WfUPByh47tf2aPzp09PzhlXVcFPHrI4p8VyI2AwiZr99d0eSrrRrhuRktqKW+AzfHV2",
	"o3P8KJcopN4tj7J2CNDac6mne+mmr132FYQqWUqfRufzs0Rydy/QvHuL4gh4butjXQBiFgtoqj/fg+UG",
	"m2K8OcLC2A7WDZvX2z3m+gXOnz6+CrJTEMYrhub6NrjhIcpfG2/08VCzP5zHywxPnv4H0lUOLWrnukPi",
	"fl+cojzersZ69jjdZY5EYtTSBhvficBfyjW0WE3BWwfYproBXgcFOA0TtvszqRc0ShfghZKpmEmFZIic",
	"nak9Rg62VhBLETTh29mVN3QLqxn9LcDSKLx03YRgrKJGH9oqkTc0z0dBpAWeF4DZYci/UglVuFN2rcp+",
	"ew28+zgodanxanxp9S4rDTu3866PfrTZdOL5vhI3I7Xv7ImGRPcnaEGf+wnakCWhhNZofX8UeqXNxjE+",
	"N7XHZKtdwqmMICBX3PYudfQmevF7Jakk1q8wFFII0FTL2MRd4tw0/rmWTs4VNN0HPgpTU8bTppd/i8e8",
	"t4wqjrIfmVG13GrEcQfpEJ6dIMuDAhR2I8ZQjdq04+2wpbH2ObDaxV1QP5zn+CoaOrsGTM0aHXMYEW/q",
	"qqHY1FaXQ1srjgmyVwLKyiC/L5iFE1vrMDHi4wBGU44N6ynxKKs6ALZxTXvMkZ5w0hDUo5qKpgv5ORRd",
	"e7vyJcaMCeV4W+swUveNUr3hNOJRed7Znb+chgX3llVxDcOnMV4Sv1Pe/my5tLDkHvoXNV1TW4pE+rbW",
	"irpJzjVo6F7k+lXjCTd0LSzoDKllcLRUHWpfxkrgrrYQ7pi1fQCEyz8xTq68W9LO/8eC/wKUn4RxjtAN",
	"pZv1GB54oKFhwwrgtqkBhnH/kItOutsjXY9RGj2J7W2kl66FMQVLx1ZQecapDEW675TZYFKEFhj6BtGO",
	"ufdWzmsPIqX3L8G3/e5D8e9rbpE/MWiJvGtvyAerD6Xj/t0JND+3L03rdcJunKYN50yPs4SdudVxXb03",
	"nxkwZxLG15xcw75DxEnd/WHUcdO/I28brlj2SYHPB0jx5vaE3Es6uztkcYRvvM6Gfye0etGzN65YbHOT",
	"OaSKji1kfWmc49Vp27q8vizerhrZaIr4bknvR2Dup4LcjDQeWz7uBt46TvwekXIbIXW95B5tC7rQPQhp",
	"wk+SKMxXY+s0IV1qVrrTLx4zVX+1V8ZvwRm1hve07BYyHoHIM3bZjpmekiO5zMJldTpRe4lu2/4CTviV",
	"HO4Y6JPe5NSwujH8Lp1d+uYwtyhi/hzv+LBCah87PHnzIwquqQSuwU7ZW6iAB1fk0BdxNSD5QxYuHyQL",
	"fvEtAzdy7PWq+7Gr7pcjjjCsFx2HpGaVhQVYCj+MFWAnbL7TnblnU4vKzngXXTUamdLHEPlxvaJrkfFk",
	"lDOmLG43DhyFO3tCnZuY2L+ikfuLRibjUF5tQyejm8zPubXb7nayaW/wOuhfep+E35SKV5HYZbaC7QXN",
	"xl5mSQBhP0nlqWBOlz9C1W+QmPRrFr5No1zzexVtyhIDFm2YMnoJNlZMQmkz/mwNNaP7R5JNzN5DsThy",
	"fDEYJO7dFL8QsN6Hc54v/4Eh7tbhYO8X3dBBhysV30mhrs17BasdOrybxJChOtPc6U4mwNQLElauY63b",
	"VaAF6nxUN24hqKECERJRTG3RDNgKtm6Y0eWFMfRDcZh5uhWSh+SuYPufUT2ZhVDzNj0pNd91EtuXkcbL",
	"JHcZCIVgs4EC+pE5a9AwdyKbbqQ/ZUFhpP7WrdB/OYvvOXUdXnX6+sw1aGK4m/G9wtTcmhVoJsxGs/k2",
	"dMXwQHTPiX6rorW5wJnedORwMPnDRxQf3YaNxl5blV1khffVxekp/fxeYZy/+OPZH8+yq49X/x8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
