// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for AgentLogSeverity.
const (
	AgentLogSeverityError AgentLogSeverity = "error"
	AgentLogSeverityInfo  AgentLogSeverity = "info"
)

// Valid indicates whether the value is a known member of the AgentLogSeverity enum.
func (e AgentLogSeverity) Valid() bool {
	switch e {
	case AgentLogSeverityError:
		return true
	case AgentLogSeverityInfo:
		return true
	default:
		return false
	}
}

// Defines values for AgentLogSource.
const (
	Agent  AgentLogSource = "agent"
	System AgentLogSource = "system"
	Tool   AgentLogSource = "tool"
	User   AgentLogSource = "user"
)

// Valid indicates whether the value is a known member of the AgentLogSource enum.
func (e AgentLogSource) Valid() bool {
	switch e {
	case Agent:
		return true
	case System:
		return true
	case Tool:
		return true
	case User:
		return true
	default:
		return false
	}
}

// Defines values for DataChangeOp.
const (
	Delete DataChangeOp = "delete"
	Insert DataChangeOp = "insert"
	Update DataChangeOp = "update"
)

// Valid indicates whether the value is a known member of the DataChangeOp enum.
func (e DataChangeOp) Valid() bool {
	switch e {
	case Delete:
		return true
	case Insert:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for Modality.
const (
	Image     Modality = "image"
	Knowledge Modality = "knowledge"
	Lcm       Modality = "lcm"
	Llm       Modality = "llm"
	Memory    Modality = "memory"
	Phone     Modality = "phone"
	Search    Modality = "search"
	Sts       Modality = "sts"
	Stt       Modality = "stt"
	Tts       Modality = "tts"
)

// Valid indicates whether the value is a known member of the Modality enum.
func (e Modality) Valid() bool {
	switch e {
	case Image:
		return true
	case Knowledge:
		return true
	case Lcm:
		return true
	case Llm:
		return true
	case Memory:
		return true
	case Phone:
		return true
	case Search:
		return true
	case Sts:
		return true
	case Stt:
		return true
	case Tts:
		return true
	default:
		return false
	}
}

// Defines values for ListAgentLogsParamsSeverity.
const (
	ListAgentLogsParamsSeverityError ListAgentLogsParamsSeverity = "error"
	ListAgentLogsParamsSeverityInfo  ListAgentLogsParamsSeverity = "info"
)

// Valid indicates whether the value is a known member of the ListAgentLogsParamsSeverity enum.
func (e ListAgentLogsParamsSeverity) Valid() bool {
	switch e {
	case ListAgentLogsParamsSeverityError:
		return true
	case ListAgentLogsParamsSeverityInfo:
		return true
	default:
		return false
	}
}

// Defines values for StreamAgentLogsParamsSeverity.
const (
	StreamAgentLogsParamsSeverityError StreamAgentLogsParamsSeverity = "error"
	StreamAgentLogsParamsSeverityInfo  StreamAgentLogsParamsSeverity = "info"
)

// Valid indicates whether the value is a known member of the StreamAgentLogsParamsSeverity enum.
func (e StreamAgentLogsParamsSeverity) Valid() bool {
	switch e {
	case StreamAgentLogsParamsSeverityError:
		return true
	case StreamAgentLogsParamsSeverityInfo:
		return true
	default:
		return false
	}
}

// AgentLog defines model for AgentLog.
type AgentLog struct {
	AgentId    string                  `json:"agent_id"`
	ConfigId   string                  `json:"config_id"`
	Cursor     *string                 `json:"cursor,omitempty"`
	Details    *map[string]interface{} `json:"details,omitempty"`
	EventType  string                  `json:"event_type"`
	Id         string                  `json:"id"`
	IngestedAt time.Time               `json:"ingested_at"`
	Message    string                  `json:"message"`
	OccurredAt time.Time               `json:"occurred_at"`
	SessionId  string                  `json:"session_id"`
	Severity   AgentLogSeverity        `json:"severity"`
	Source     AgentLogSource          `json:"source"`
	UserId     *string                 `json:"user_id,omitempty"`
}

// AgentLogSeverity defines model for AgentLog.Severity.
type AgentLogSeverity string

// AgentLogSource defines model for AgentLog.Source.
type AgentLogSource string

// AgentLogPage defines model for AgentLogPage.
type AgentLogPage struct {
	Coverage     string     `json:"coverage"`
	DroppedLogs  int64      `json:"dropped_logs"`
	HasMore      bool       `json:"has_more"`
	Items        []AgentLog `json:"items"`
	NextCursor   string     `json:"next_cursor"`
	ResumeCursor string     `json:"resume_cursor"`
}

// DataChange One thing that happened to one row of the calling app's data.
type DataChange struct {
	At time.Time `json:"at"`

	// Key What identifies the row, which is all a delete has.
	Key map[string]interface{} `json:"key"`
	Op  DataChangeOp           `json:"op"`

	// Row The row as it now reads, absent for a delete and never carrying a credential.
	Row *map[string]interface{} `json:"row,omitempty"`

	// Seq Where this sits in the order changes happened, and the cursor to resume from.
	Seq int64 `json:"seq"`

	// Table Which table the row is in.
	//
	// Example: agent_configs
	Table string `json:"table"`
}

// DataChangeOp defines model for DataChange.Op.
type DataChangeOp string

// DataChangePage defines model for DataChangePage.
type DataChangePage struct {
	// CaughtUp Nothing else has happened yet, which is when a switchover is safe: point your SDKs at the new deployment, wait for this to be true once more, and stop.
	CaughtUp *bool        `json:"caught_up,omitempty"`
	Changes  []DataChange `json:"changes"`

	// Cursor What to pass as `after` next time.
	Cursor int64 `json:"cursor"`
}

// DataImport defines model for DataImport.
type DataImport struct {
	// Cursor The cursor the export named, to ask the other deployment for changes from.
	Cursor *int64 `json:"cursor,omitempty"`

	// Rows How many rows were written.
	Rows int64 `json:"rows"`

	// Tables How many of them went into each table.
	Tables *map[string]int64 `json:"tables,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Modality What kind of work was done. The first seven are routed across providers; sts is speech to speech, one native audio model in place of a transcriber, a text model and a voice. lcm is a large classifier model: it answers a question about a piece of text with a typed value and the probability behind it rather than with prose, which is what a guardrail asks before a reply is spoken. image is pictures drawn from a prompt. Memory, knowledge and phone are recorded but not routed, since there is one memory store, one knowledge base and one vendor per number, so the provider paths do not serve them while the statistics paths do.
//
// Example: tts
type Modality string

// SessionID defines model for SessionID.
type SessionID = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListAgentLogsParams defines parameters for ListAgentLogs.
type ListAgentLogsParams struct {
	ConfigId  *string                      `form:"config_id,omitempty" json:"config_id,omitempty"`
	SessionId *string                      `form:"session_id,omitempty" json:"session_id,omitempty"`
	UserId    *string                      `form:"user_id,omitempty" json:"user_id,omitempty"`
	Severity  *ListAgentLogsParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`

	// Source Comma-separated user/agent/tool/system sources.
	Source *string    `form:"source,omitempty" json:"source,omitempty"`
	Q      *string    `form:"q,omitempty" json:"q,omitempty"`
	From   *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To     *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Cursor *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAgentLogsParamsSeverity defines parameters for ListAgentLogs.
type ListAgentLogsParamsSeverity string

// StreamAgentLogsParams defines parameters for StreamAgentLogs.
type StreamAgentLogsParams struct {
	ConfigId  *string                        `form:"config_id,omitempty" json:"config_id,omitempty"`
	SessionId *string                        `form:"session_id,omitempty" json:"session_id,omitempty"`
	UserId    *string                        `form:"user_id,omitempty" json:"user_id,omitempty"`
	Severity  *StreamAgentLogsParamsSeverity `form:"severity,omitempty" json:"severity,omitempty"`

	// Source Comma-separated user/agent/tool/system sources.
	Source      *string    `form:"source,omitempty" json:"source,omitempty"`
	Q           *string    `form:"q,omitempty" json:"q,omitempty"`
	From        *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To          *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Cursor      *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	LastEventID *string    `json:"Last-Event-ID,omitempty"`
}

// StreamAgentLogsParamsSeverity defines parameters for StreamAgentLogs.
type StreamAgentLogsParamsSeverity string

// PluginOAuthCallbackParams defines parameters for PluginOAuthCallback.
type PluginOAuthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// WatchSessionParams defines parameters for WatchSession.
type WatchSessionParams struct {
	// Interim Also send `hearing` frames, which are the words as they are revised.
	Interim *bool `form:"interim,omitempty" json:"interim,omitempty"`

	// Decisions Send `decision` frames.
	Decisions *bool `form:"decisions,omitempty" json:"decisions,omitempty"`

	// ReplayPendingTools Replay pending live voice tool requests to a durable tool host.
	ReplayPendingTools *bool `form:"replay_pending_tools,omitempty" json:"replay_pending_tools,omitempty"`
}

// ListDataChangesParams defines parameters for ListDataChanges.
type ListDataChangesParams struct {
	// After The cursor the last page ended at.
	After *int64 `form:"after,omitempty" json:"after,omitempty"`
	Limit *int   `form:"limit,omitempty" json:"limit,omitempty"`
}

// DispatchCallsParams defines parameters for DispatchCalls.
type DispatchCallsParams struct {
	// Capacity How much work this worker takes at once, calls and messages together.
	Capacity *int `form:"capacity,omitempty" json:"capacity,omitempty"`

	// Active How much work this worker is still running from before it reconnected, which the router counts against its capacity until each piece is reported `done`. Sending this at all, even as 0, is what says the worker reports `done`; one that leaves it out is held only to the depth of its queue.
	Active *int `form:"active,omitempty" json:"active,omitempty"`

	// Handles The kinds of work this worker accepts, comma separated. Absent is both. A worker that only answers in writing says `message`, so a caller is never left listening to a phone it would have dropped.
	Handles *string `form:"handles,omitempty" json:"handles,omitempty"`
}
