---
name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: '.github/labeler.yml'
          sync-labels: "true"
