name: Integration (pre-release / release)
on:
  push:
    tags:
      - 'v*'          # run when you push a version tag like v1.2.3
  release:
    types: [published] # run when a GitHub Release is published
  workflow_dispatch: {}

jobs:
  integration:
    uses: ./.github/workflows/run_tests.yml
    with:
      marker: 'integration'
    secrets: inherit

  build-core:
    name: Build & Test Core SDK
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/python-uv-setup

      - name: Build all distributions
        run: |
          uv build --all -o dist

      - name: Extract package version (hatch via uv)
        id: get_version
        working-directory: agents-core
        run: |
          VERSION=$(uv run -q hatch version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

#      - name: Publish core to TestPyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          repository-url: https://test.pypi.org/legacy/
#          packages-dir: dist
#        environment:
#          name: testpypi

  test-core-index:
    name: Verify Core from TestPyPI
    needs: build-core
    runs-on: ubuntu-latest
    env:
      UV_NO_SOURCES: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/python-uv-setup

      - name: Install core from TestPyPI using uv
        run: |
          uv pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple getstream==${{ needs.build-core.outputs.version }}

      - name: Run core tests against TestPyPI artifact
        run: |
          UV_NO_SOURCES=1 uv run pytest tests/ --ignore=getstream/plugins
